DECLARE @SqlStatement NVARCHAR(MAX)
SELECT @SqlStatement = 
    COALESCE(@SqlStatement, N'') + N'DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].' + QUOTENAME(TABLE_NAME) + N';' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'EL_MONSTRUO_DEL_LAGO_MASER' and TABLE_TYPE = 'BASE TABLE'

PRINT @SqlStatement

