USE [GD1C2018]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXroles] DROP CONSTRAINT [FK__usuariosX__id_us__7128A7F2]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXroles] DROP CONSTRAINT [FK__usuariosX__id_ro__703483B9]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXhoteles] DROP CONSTRAINT [FK__usuariosX__id_us__76E18148]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXhoteles] DROP CONSTRAINT [FK__usuariosX__id_ho__77D5A581]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] DROP CONSTRAINT [FK__rolesXfun__id_ro__7BA63665]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] DROP CONSTRAINT [FK__rolesXfun__id_fu__7C9A5A9E]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservasXhabitaciones] DROP CONSTRAINT [FK__reservasX__id_re__6E4C3B47]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservasXhabitaciones] DROP CONSTRAINT [FK__reservasX__id_ha__6F405F80]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservas] DROP CONSTRAINT [FK__reservas__id_reg__74F938D6]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservas] DROP CONSTRAINT [FK__reservas__id_est__75ED5D0F]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservas] DROP CONSTRAINT [FK__reservas__id_cli__7405149D]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[items_factura] DROP CONSTRAINT [FK__items_fac__id_fa__679F3DB8]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[items_factura] DROP CONSTRAINT [FK__items_fac__id_co__689361F1]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[hotelesXregimenes] DROP CONSTRAINT [FK__hotelesXr__id_re__79BDEDF3]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[hotelesXregimenes] DROP CONSTRAINT [FK__hotelesXr__id_ho__78C9C9BA]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[hoteles] DROP CONSTRAINT [FK__hoteles__id_pais__7AB2122C]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[habitaciones] DROP CONSTRAINT [FK__habitacio__id_ti__6D58170E]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[habitaciones] DROP CONSTRAINT [FK__habitacio__id_ho__6C63F2D5]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[generacion_modificacion_reservas] DROP CONSTRAINT [FK__generacio__id_us__7F76C749]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[generacion_modificacion_reservas] DROP CONSTRAINT [FK__generacio__id_re__7E82A310]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[facturas] DROP CONSTRAINT [FK__facturas__id_for__60F24029]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[facturas] DROP CONSTRAINT [FK__facturas__id_est__5FFE1BF0]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[estadias] DROP CONSTRAINT [FK__estadias__id_usu__6B6FCE9C]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[estadias] DROP CONSTRAINT [FK__estadias__id_usu__6A7BAA63]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[estadias] DROP CONSTRAINT [FK__estadias__id_res__6987862A]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cuentas] DROP CONSTRAINT [FK__cuentas__id_usua__5F09F7B7]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[consumos] DROP CONSTRAINT [FK__consumos__id_hab__63CEACD4]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[consumos] DROP CONSTRAINT [FK__consumos__id_est__62DA889B]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[consumos] DROP CONSTRAINT [FK__consumos__id_con__61E66462]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[clientesXestadias] DROP CONSTRAINT [FK__clientesX__id_es__65B6F546]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[clientesXestadias] DROP CONSTRAINT [FK__clientesX__id_cl__64C2D10D]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[clientes] DROP CONSTRAINT [FK__clientes__id_tip__5D21AF45]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[clientes] DROP CONSTRAINT [FK__clientes__id_pai__5E15D37E]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cierres_temporales_hotel] DROP CONSTRAINT [FK__cierres_t__id_ho__7D8E7ED7]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cierres_temporales_habitacion] DROP CONSTRAINT [FK__cierres_t__id_ha__66AB197F]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cancelaciones_reserva] DROP CONSTRAINT [FK__cancelaci__id_us__7310F064]
GO
ALTER TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cancelaciones_reserva] DROP CONSTRAINT [FK__cancelaci__id_re__721CCC2B]
GO
/****** Object:  View [EL_MONSTRUO_DEL_LAGO_MASER].[clientes_completos]    Script Date: 24/6/2018 22:27:10 ******/
DROP VIEW [EL_MONSTRUO_DEL_LAGO_MASER].[clientes_completos]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXroles]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXroles]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXhoteles]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuariosXhoteles]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[usuarios]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[usuarios]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[tipos_habitacion]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[tipos_habitacion]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[tipos_documento]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[tipos_documento]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[roles]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[roles]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[reservasXhabitaciones]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservasXhabitaciones]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[reservas]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[reservas]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[regimenes]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[regimenes]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[paises]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[paises]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[migracion_errores]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[migracion_errores]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[items_factura]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[items_factura]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[hotelesXregimenes]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[hotelesXregimenes]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[hoteles]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[hoteles]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[habitaciones]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[habitaciones]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[generacion_modificacion_reservas]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[generacion_modificacion_reservas]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[funcionalidades]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[funcionalidades]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[formas_de_pago]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[formas_de_pago]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[facturas]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[facturas]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[estados_reserva]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[estados_reserva]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[estadias]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[estadias]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[cuentas]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cuentas]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[consumos]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[consumos]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[consumibles]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[consumibles]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[clientesXestadias]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[clientesXestadias]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[clientes]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[clientes]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[cierres_temporales_hotel]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cierres_temporales_hotel]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[cierres_temporales_habitacion]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cierres_temporales_habitacion]
GO
/****** Object:  Table [EL_MONSTRUO_DEL_LAGO_MASER].[cancelaciones_reserva]    Script Date: 24/6/2018 22:27:10 ******/
DROP TABLE [EL_MONSTRUO_DEL_LAGO_MASER].[cancelaciones_reserva]
GO
/****** Object:  UserDefinedFunction [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_COSTO_DIARIO_ESTADIA]    Script Date: 24/6/2018 22:27:10 ******/
DROP FUNCTION [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_COSTO_DIARIO_ESTADIA]
GO
/****** Object:  UserDefinedFunction [EL_MONSTRUO_DEL_LAGO_MASER].[MINDATE]    Script Date: 24/6/2018 22:27:10 ******/
DROP FUNCTION [EL_MONSTRUO_DEL_LAGO_MASER].[MINDATE]
GO
/****** Object:  UserDefinedFunction [EL_MONSTRUO_DEL_LAGO_MASER].[MAXDATE]    Script Date: 24/6/2018 22:27:10 ******/
DROP FUNCTION [EL_MONSTRUO_DEL_LAGO_MASER].[MAXDATE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[VALIDAR_ROL_USUARIO]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[VALIDAR_ROL_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[VALIDAR_DOCUMENTO_UNICO_CLIENTE]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[VALIDAR_DOCUMENTO_UNICO_CLIENTE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[VALIDAR_CORREO_UNICO_CLIENTE]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[VALIDAR_CORREO_UNICO_CLIENTE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HOTELES_RESERVAS_CANCELADAS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HOTELES_RESERVAS_CANCELADAS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HOTELES_MAYOR_CANTIDAD_CONSUMOS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HOTELES_MAYOR_CANTIDAD_CONSUMOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HOTELES_DIAS_CERRADO]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HOTELES_DIAS_CERRADO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HABITACIONES_MAYOR_CANTIDAD_DIAS_ESTADIAS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_HABITACIONES_MAYOR_CANTIDAD_DIAS_ESTADIAS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_CLIENTES_PUNTOS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[TOP5_CLIENTES_PUNTOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[REGIMENES_USADOS_POR_RESERVAS_DE_HOTEL]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[REGIMENES_USADOS_POR_RESERVAS_DE_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_USUARIOS_FILTRADOS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_USUARIOS_FILTRADOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_USUARIO_DUMMY]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_USUARIO_DUMMY]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_TIPOS_HABITACION_RESERVA]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_TIPOS_HABITACION_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_TIPOS_HABITACION]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_TIPOS_HABITACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_TIPOS_DOCUMENTO]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_TIPOS_DOCUMENTO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROLES_FILTRADOS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROLES_FILTRADOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROLES_DE_UN_USUARIO]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROLES_DE_UN_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROLES]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROLES]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROL_GUEST]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ROL_GUEST]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_RESERVA_APTA_ESTADIA]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_RESERVA_APTA_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_RESERVA]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMENES_DE_UN_HOTEL]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMENES_DE_UN_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMENES_ACTIVOS_DE_HOTEL]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMENES_ACTIVOS_DE_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMENES]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMENES]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMEN_DE_ESTADIA]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMEN_DE_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMEN_ALL_INCLUSIVE_MODERADO]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMEN_ALL_INCLUSIVE_MODERADO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMEN_ALL_INCLUSIVE]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_REGIMEN_ALL_INCLUSIVE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_PAISES]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_PAISES]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_PAIS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_PAIS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTELES_FILTRADOS]    Script Date: 24/6/2018 22:27:10 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTELES_FILTRADOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTELES_DE_UN_USUARIO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTELES_DE_UN_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTELES]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTELES]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTEL_DE_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HOTEL_DE_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_FILTRADAS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_FILTRADAS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_DISPONIBLES_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_DISPONIBLES_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_DE_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_DE_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_DE_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_HABITACIONES_DE_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_FUNCIONALIDADES_DE_ROL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_FUNCIONALIDADES_DE_ROL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_FUNCIONALIDADES]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_FUNCIONALIDADES]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_FORMAS_DE_PAGO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_FORMAS_DE_PAGO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ESTADIA_DE_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ESTADIA_DE_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_DATOS_ESTADIA_FACTURACION]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_DATOS_ESTADIA_FACTURACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CONSUMOS_DE_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CONSUMOS_DE_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CONSUMIBLES_FILTRADOS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CONSUMIBLES_FILTRADOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTES_FILTRADOS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTES_FILTRADOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTES_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTES_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTES_COMPLETOS_FILTRADOS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTES_COMPLETOS_FILTRADOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTE_DE_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CLIENTE_DE_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CANTIDAD_RESERVAS_EN_PERIODO_HOTEL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[OBTENER_CANTIDAD_RESERVAS_EN_PERIODO_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_USUARIO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_ROL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_ROL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_HOTEL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_HABITACION]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_HABITACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_CONSUMO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_CONSUMO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_CLIENTE]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MODIFICAR_CLIENTE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[MIGRAR_DATOS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[MIGRAR_DATOS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[LOGIN_USUARIO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[LOGIN_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_USUARIO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_NUEVO_ROL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_NUEVO_ROL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_NUEVO_CLIENTE_SIN_VALIDACION]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_NUEVO_CLIENTE_SIN_VALIDACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_NUEVO_CLIENTE]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_NUEVO_CLIENTE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_HABITACION]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_HABITACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_CLIENTE_PREEXISTENTE]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_CLIENTE_PREEXISTENTE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_CIERRE_TEMPORAL_HOTEL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_CIERRE_TEMPORAL_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_CIERRE_TEMPORAL_HABITACION]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INSERTAR_CIERRE_TEMPORAL_HABITACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[INGRESAR_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[INGRESAR_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[HABITACION_RESERVADA_EN_INTERVALO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[HABITACION_RESERVADA_EN_INTERVALO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[EGRESAR_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[EGRESAR_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[DESHABILITAR_USUARIO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[DESHABILITAR_USUARIO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[DESHABILITAR_ROL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[DESHABILITAR_ROL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[DESHABILITAR_CLIENTE]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[DESHABILITAR_CLIENTE]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_TIPOS_HABITACION]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_TIPOS_HABITACION]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_RESERVAS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_RESERVAS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_FACTURAS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_FACTURAS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_FACTURA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_FACTURA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_CONSUMIBLES]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CREAR_CONSUMIBLES]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CERRAR_CONSUMO_ESTADIA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CERRAR_CONSUMO_ESTADIA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CANCELAR_RESERVAS_VENCIDAS]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CANCELAR_RESERVAS_VENCIDAS]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[CANCELAR_RESERVA]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[CANCELAR_RESERVA]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[BORRAR_CONSUMO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[BORRAR_CONSUMO]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[AGREGAR_NUEVO_HOTEL]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[AGREGAR_NUEVO_HOTEL]
GO
/****** Object:  StoredProcedure [EL_MONSTRUO_DEL_LAGO_MASER].[AGREGAR_CONSUMO]    Script Date: 24/6/2018 22:27:11 ******/
DROP PROCEDURE [EL_MONSTRUO_DEL_LAGO_MASER].[AGREGAR_CONSUMO]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeRoles]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeRoles]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeRegimenes]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeRegimenes]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeItems]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeItems]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeHoteles]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeHoteles]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeHabitaciones]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeHabitaciones]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeFuncionalidades]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeFuncionalidades]
GO
/****** Object:  UserDefinedTableType [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeClientes]    Script Date: 24/6/2018 22:27:11 ******/
DROP TYPE [EL_MONSTRUO_DEL_LAGO_MASER].[listaDeClientes]
GO
/****** Object:  Schema [EL_MONSTRUO_DEL_LAGO_MASER]    Script Date: 24/6/2018 22:27:11 ******/
DROP SCHEMA [EL_MONSTRUO_DEL_LAGO_MASER]
GO

