INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[roles] VALUES ('Guest', 1);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[roles] VALUES ('Administrador', 1);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[roles] VALUES ('Recepcionista', 1);

GO

