INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (1, 1);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (1, 2);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (1, 3);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 1);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 2);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 3);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 4);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 5);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 6);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 7);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 8);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 9);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 10);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 11);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 12);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 13);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 14);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 15);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 16);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 17);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (2, 18);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 1);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 2);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 3);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 7);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 8);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 15);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 16);
INSERT INTO [EL_MONSTRUO_DEL_LAGO_MASER].[rolesXfuncionalidades] VALUES (3, 17);

GO

